# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1e3c3733e6c6ac1332ac84e29d29ac7773b164080451f53bde3e77cbd6a203f92db7870aa33a55b7aa6718aa65d887b88857eebc3f0a658ee8b3f294096cef7

test:
  secret_key_base: 86eeb1e3876d53dcb0a8ff2cb5df065347966f220f68a46bf0aab9eb1f55410f6bff3b0354b1ab6f52422fb2238c6d7b9c94dc5992264857b75cabaf78cfe0de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
